### ISSUE TITLE
add leading zeros 

### ISSUE THREAD

**Issue by vomov** [Xonshiz/comic-dl#18]
I use comicrack for reading the downloaded comics, and I have a batch script that packs the folders into cb7 files. Because Comicrack is stupid with the numbering, I need to add leading zeros to the filenames. 

Would this be possible?

**Comment by Xonshiz** [comment]
I can't promise anything. But, I will surely look into this.

**Comment by Xonshiz** [comment]
This should be fixed now.

**Comment by jaxxa** [comment]
This still appears to be an issue for me. It is prepending 0 to all of the file names, when it should only prepend it to filenames smaller than the the maximum length. This is keeping it in the incorrect order as before.

For example now it is going:

01.jpg
010.jpg
011.jpg
012.jpg
...
019.jpg
02.jpg
020.jpg
...

I am using the latest windows binary release.

Here is the Gist, although this is not throwing an error so I dont think that it will be of any help.

https://gist.github.com/jaxxa/555bf9227087460760337ee2b27297ea

**Comment by Xonshiz** [comment]
Open a separated issue please. And also, what did you mean by this line 
`when it should only prepend it to filenames smaller than the the maximum length.`

It would be great if you could elaborate this naming sequence you want.

**Comment by vomov** [comment]
I suspect he means that it should only pad until it reaches the longest number. For example, if a comic has 30 pages, then it should pad 4 to 04, and leave anything with two digits alone (12 stays 12), while if a comic has 200 pages, 4 should become 004, and 12 should become 012.

**Comment by Xonshiz** [comment]
I hope he doesn't mean this. xD!
Too much work hahah

**Comment by jaxxa** [comment]
Ok, I will log it as a new issue when I get Home.

**Comment by Xonshiz** [comment]
I had to remove this feature to fix a few things. I'm re-opening this and will try to bring this back in a few days.

**Comment by DyeffersonAz** [comment]
Is this enabled right now?

**Comment by Xonshiz** [comment]
Nope.

**Comment by DyeffersonAz** [comment]
What is these THINGS???

**Comment by Xonshiz** [comment]
?

**Comment by DyeffersonAz** [comment]
![image](https://user-images.githubusercontent.com/16638560/36200698-ac59c228-1164-11e8-89c3-5ed025f596e1.png)

**Comment by Xonshiz** [comment]
Check the code as on Jan 1, you should see the changes I made, the feature I added or a bug I fixed. Plus, the previous implementation was very bad, hence, had to remove it.
