### ISSUE TITLE
Issue with Leading zeros.

### ISSUE THREAD

**Issue by jaxxa** [Xonshiz/comic-dl#30]
Initially posted as a comment on #18 

First of all thanks for the awesome program.

This still appears to be an issue for me. It is prepending 0 to all of the file names. What should happen is that it add leading zeroes in order to make all file names the same length. 

So if in total there are between 10 and 99 images one zero will get added to the number 1-9 so that all image files have 2 characters.
 If there are between 100-999 images two zeroes will be added to the number 1-9 and one Zero to the number 10-99 so that all image files have 3 characters.

As it is currently working one zero is added to every image. This is keeping it in the incorrect order as before. An example order tat can be produced now is:

01.jpg
010.jpg
011.jpg
012.jpg
...
019.jpg
02.jpg
020.jpg
...

This is the same out of order issue that happens before the Leading zeros were implemented so if this cant be fixed I feel that it would be better to revert the feature entirely.

If the program does not know the total number of images when it starts you could possibly add a parameter for the number of characters required and leave it up-to the user. Or you could save all of the images and then do a rename Pass once they are all downloaded.
  
I have made a prototype program in C# that renames the files after they are all saved and creates a .cbz file if you would like to look at what I mean. (currently hardcoded, you would need to compile it or just read the code.)

https://github.com/jaxxa/ComicCreator/blob/master/ComicCreator/Form1.cs

I am using the latest windows binary release.

Here is the Gist, although this is not throwing an error so I dont think that it will be of any help.

https://gist.github.com/jaxxa/555bf9227087460760337ee2b27297ea

**Comment by Xonshiz** [comment]
UH sorry, I just got time to check this. I'll look into this in a day or two.

**Comment by sethcohn** [comment]
+1

**Comment by Xonshiz** [comment]
Fixed this issue now. Please check on your side.

**Comment by jaxxa** [comment]
From the quick test that I have done it looks to be working on as I would expect on readcomiconline.to but www.mangahere.co is still having the old functionality of just adding a 0 in front of everything.

**Comment by Xonshiz** [comment]
Okay, will update that part :)

**Comment by Xonshiz** [comment]
Fixed now!
